Output .env when sourcing it fails in a docker container

diff --git a/docker/multi-process/scripts/init b/docker/multi-process/scripts/init
--- a/docker/multi-process/scripts/init
+++ b/docker/multi-process/scripts/init
@@ -47,7 +47,16 @@ echo "RAILS_LOG_TO_STDOUT=true" >> .env
 echo "RAILS_SERVE_STATIC_FILES=true" >> .env
 
 chmod ugo+r /app/.env
+
+set +e
 source /app/.env
+if [ $? -ne 0 ]; then
+  echo "Invalid or un-escaped characters in .env:"
+  cat .env
+  exit 1
+fi
+set -e
+
 sudo -u huginn -H -E bundle install --without test development --path vendor/bundle
 
 # use default port number if it is still not set
diff --git a/docker/single-process/scripts/init b/docker/single-process/scripts/init
--- a/docker/single-process/scripts/init
+++ b/docker/single-process/scripts/init
@@ -33,7 +33,15 @@ eval "echo RAILS_LOG_TO_STDOUT=true" >> .env
 eval "echo RAILS_SERVE_STATIC_FILES=true" >> .env
 
 chmod ugo+r /app/.env
+
+set +e
 source /app/.env
+if [ $? -ne 0 ]; then
+  echo "Invalid or un-escaped characters in .env:"
+  cat .env
+  exit 1
+fi
+set -e
 
 # use default port number if it is still not set
 case "${DATABASE_ADAPTER}" in
